---
name: "jellyfin-plugin-auto-collections"
guid: "06ebf4a9-1326-4327-968d-8da00e1ea2eb"
version: "19" # Please increment with each pull request
jellyfin_version: "10.5.0" # The earliest binary-compatible version
owner: "jellyfin"
nicename: "Auto Collections"
description: "Automatically creates and maintains collections by matching movies and TV series based on their titles, genres, studios, actors, or directors. Supports case-sensitive matching and custom collection names."
overview: "Creates dynamic collections based on Title, Genre, Studio, Actor, or Director matching"
category: "Metadata"
artifacts:
  - "Jellyfin.Plugin.AutoCollections.dll"
build_type: "dotnet"
dotnet_configuration: "Release"
dotnet_framework: "netstandard2.1"
