---
name: "jellyfin-plugin-auto-collections-dev"
guid: "06ebf4a9-1326-4327-968d-8da00e1ea2eb"
version: "21" # Please increment with each pull request
jellyfin_version: "10.5.0" # The earliest binary-compatible version
owner: "jellyfin"
nicename: "Auto Collections"
description: "Automatically create Auto Collections based on matching strings in the metadata."
overview: "Automatically create Auto Collections based on matching strings in the metadata."
category: "Metadata"
artifacts:
  - "Jellyfin.Plugin.AutoCollections.dll"
build_type: "dotnet"
dotnet_configuration: "Release"
dotnet_framework: "netstandard2.1"
